saudaçoes = input('Olá! deseja continuar para um dos meus primeiros programas? Se estiver pronto, pressione qualquer tecla e dê enter')
algo = input('Digite algo para saber algumas de suas classificações: ')
print('A classe de {} é: ' .format(algo),type(algo) )
print('{} é um algarismo?' .format(algo), algo.isnumeric())
print('{} faz parte do alfabeto?' .format(algo), algo.isalpha())
print('{} está todo em maiúsculo? ' .format(algo), algo.isupper())
print('{} está todo em minúsculo? ' .format(algo), algo.islower())
print('{} é composto somente por espaços?' .format(algo), algo.isspace())
print('{} está capitalizado? ' .format(algo), algo.istitle())
print('{} é alfanumérico? ' .format(algo), algo.isalnum())
print('Muito obrigado por utilizar este programa! Para sair, basta pressionar qualquer tecla e dar enter.')
input()